"""
Alert system for the trading platform.
Supports console, file-based, and webhook-based alerting
for risk events, trade notifications, and system health.
"""

import json
import os
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional

import requests
from loguru import logger


class AlertLevel(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(Enum):
    """Types of alerts generated by the system."""
    TRADE_EXECUTED = "trade_executed"
    POSITION_CLOSED = "position_closed"
    STOP_LOSS_HIT = "stop_loss_hit"
    TAKE_PROFIT_HIT = "take_profit_hit"
    DRAWDOWN_WARNING = "drawdown_warning"
    DAILY_LOSS_WARNING = "daily_loss_warning"
    TRADING_HALTED = "trading_halted"
    SYSTEM_ERROR = "system_error"
    STRATEGY_SWITCH = "strategy_switch"
    CONNECTION_LOST = "connection_lost"


class AlertManager:
    """
    Manages alerts across multiple notification channels.

    Channels:
        - Console (always active via loguru)
        - File-based alerts log
        - Slack webhook (optional, configured via environment)
        - Email (optional, configured via environment)
    """

    def __init__(
        self,
        slack_webhook_url: Optional[str] = None,
        alert_log_dir: Optional[str] = None,
    ):
        """
        Initialize the alert manager.

        Args:
            slack_webhook_url: Slack incoming webhook URL for notifications
            alert_log_dir: Directory for alert log files
        """
        # Slack webhook from parameter or environment variable
        self.slack_webhook_url = slack_webhook_url or os.environ.get("SLACK_WEBHOOK_URL")

        # Alert log file
        log_dir = alert_log_dir or os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "logs"
        )
        os.makedirs(log_dir, exist_ok=True)
        self.alert_log_path = os.path.join(log_dir, "alerts.log")

        # Alert history for dashboard display
        self.alert_history: List[dict] = []
        self.max_history = 1000

    def send_alert(
        self,
        alert_type: AlertType,
        level: AlertLevel,
        message: str,
        data: Optional[Dict] = None,
    ) -> None:
        """
        Send an alert through all configured channels.

        Args:
            alert_type: Type of alert event
            level: Severity level
            message: Human-readable alert message
            data: Optional additional data payload
        """
        alert = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "type": alert_type.value,
            "level": level.value,
            "message": message,
            "data": data or {},
        }

        # Store in history
        self.alert_history.append(alert)
        if len(self.alert_history) > self.max_history:
            self.alert_history = self.alert_history[-self.max_history:]

        # Console logging (always active)
        self._log_to_console(alert)

        # File logging
        self._log_to_file(alert)

        # Slack notification for warnings and critical alerts
        if level in (AlertLevel.WARNING, AlertLevel.CRITICAL) and self.slack_webhook_url:
            self._send_slack(alert)

    def _log_to_console(self, alert: dict) -> None:
        """Log alert to console via loguru."""
        level = alert["level"]
        msg = f"🔔 [{alert['type'].upper()}] {alert['message']}"

        if level == "critical":
            logger.critical(msg)
        elif level == "warning":
            logger.warning(msg)
        else:
            logger.info(msg)

    def _log_to_file(self, alert: dict) -> None:
        """Append alert to the alerts log file."""
        try:
            with open(self.alert_log_path, "a") as f:
                f.write(json.dumps(alert) + "\n")
        except Exception as e:
            logger.error(f"Failed to write alert to file: {e}")

    def _send_slack(self, alert: dict) -> None:
        """
        Send alert to Slack via incoming webhook.

        Args:
            alert: Alert dictionary to send
        """
        if not self.slack_webhook_url:
            return

        # Format Slack message with color based on severity
        color_map = {
            "info": "#36a64f",
            "warning": "#daa520",
            "critical": "#dc3545",
        }
        color = color_map.get(alert["level"], "#888888")

        # Build Slack attachment payload
        payload = {
            "attachments": [{
                "color": color,
                "title": f"Trading Alert: {alert['type'].upper()}",
                "text": alert["message"],
                "fields": [
                    {"title": "Level", "value": alert["level"].upper(), "short": True},
                    {"title": "Time", "value": alert["timestamp"], "short": True},
                ],
                "footer": "Automated Trading System",
            }]
        }

        try:
            response = requests.post(
                self.slack_webhook_url,
                json=payload,
                timeout=10,
            )
            if response.status_code != 200:
                logger.warning(f"Slack alert failed: {response.status_code}")
        except Exception as e:
            logger.warning(f"Slack alert delivery failed: {e}")

    def get_recent_alerts(self, limit: int = 50, level: Optional[str] = None) -> List[dict]:
        """
        Get recent alerts, optionally filtered by severity level.

        Args:
            limit: Maximum number of alerts to return
            level: Optional filter by alert level

        Returns:
            List of alert dictionaries (most recent first)
        """
        alerts = self.alert_history
        if level:
            alerts = [a for a in alerts if a["level"] == level]
        return alerts[-limit:][::-1]
