"""
Abstract base class for all trading strategies.
Defines the interface for signal generation, confidence scoring,
and strategy lifecycle management.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional

import pandas as pd
from loguru import logger


class Signal(Enum):
    """Trading signal types generated by strategies."""
    STRONG_BUY = "strong_buy"
    BUY = "buy"
    HOLD = "hold"
    SELL = "sell"
    STRONG_SELL = "strong_sell"


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by a strategy.
    Contains the signal direction, confidence, and metadata.
    """
    symbol: str                          # Trading pair (e.g., "BTC/USDT")
    signal: Signal                       # Signal direction
    confidence: float                    # Confidence score (0.0 to 1.0)
    strategy_name: str                   # Name of the generating strategy
    price: float                         # Current price when signal was generated
    stop_loss: Optional[float] = None    # Suggested stop-loss price
    take_profit: Optional[float] = None  # Suggested take-profit price
    metadata: Dict = field(default_factory=dict)  # Additional strategy-specific data

    @property
    def is_buy(self) -> bool:
        """Check if this is a buy signal."""
        return self.signal in (Signal.BUY, Signal.STRONG_BUY)

    @property
    def is_sell(self) -> bool:
        """Check if this is a sell signal."""
        return self.signal in (Signal.SELL, Signal.STRONG_SELL)

    @property
    def is_strong(self) -> bool:
        """Check if this is a strong signal."""
        return self.signal in (Signal.STRONG_BUY, Signal.STRONG_SELL)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Subclasses must implement generate_signal() and get_name().
    """

    def __init__(self, config=None):
        """
        Initialize the strategy.

        Args:
            config: StrategyConfig instance for strategy parameters
        """
        from config.settings import StrategyConfig
        self.config = config or StrategyConfig()
        self._trade_count = 0
        self._cooldown_counter = 0

    @abstractmethod
    def get_name(self) -> str:
        """Return the strategy name identifier."""
        pass

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> TradeSignal:
        """
        Generate a trading signal based on current market data.

        Args:
            df: OHLCV DataFrame with technical indicators added
            symbol: Trading pair symbol

        Returns:
            TradeSignal with direction, confidence, and metadata
        """
        pass

    def should_trade(self) -> bool:
        """
        Check if the strategy is allowed to trade (cooldown check).
        Prevents overtrading by enforcing a minimum gap between signals.

        Returns:
            True if the strategy can generate a new trade signal
        """
        if self._cooldown_counter > 0:
            self._cooldown_counter -= 1
            return False
        return True

    def on_trade_executed(self) -> None:
        """
        Called when a trade signal from this strategy is executed.
        Resets the cooldown counter.
        """
        self._trade_count += 1
        self._cooldown_counter = self.config.trade_cooldown_candles
        logger.debug(
            f"Strategy '{self.get_name()}' trade #{self._trade_count}, "
            f"cooldown set to {self._cooldown_counter} candles"
        )

    def reset(self) -> None:
        """Reset strategy state (useful for backtesting)."""
        self._trade_count = 0
        self._cooldown_counter = 0

    def _neutral_signal(self, df: pd.DataFrame, symbol: str) -> TradeSignal:
        """Return a HOLD signal when no trading opportunity is found."""
        price = df.iloc[-1]["close"] if len(df) > 0 else 0.0
        return TradeSignal(
            symbol=symbol,
            signal=Signal.HOLD,
            confidence=0.0,
            strategy_name=self.get_name(),
            price=price,
        )

    def _calculate_confidence(self, factors: Dict[str, float]) -> float:
        """
        Calculate an overall confidence score from multiple factors.
        Each factor should be between 0.0 and 1.0.

        Args:
            factors: Dict of factor_name -> factor_score

        Returns:
            Weighted average confidence (0.0 to 1.0)
        """
        if not factors:
            return 0.0
        total = sum(factors.values())
        return min(1.0, max(0.0, total / len(factors)))
